version: "3"
services:
  frontend:
    container_name: frontend-next
    build: ./frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/frontend
    links:
      - backend
  backend:
    container_name: backend-hapi
    build: ./backend
    ports:
      - 3001:3001
    volumes:
      - ./backend:/backend
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - 27017:27017
    volumes:
    - ./data:/data/db
